/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Image = IDL.Vec(IDL.Nat8);
export const Church = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'nameAr' : IDL.Text,
  'nameEn' : IDL.Text,
  'descriptionAr' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'addressAr' : IDL.Text,
  'addressEn' : IDL.Text,
  'longitude' : IDL.Float64,
  'image' : IDL.Opt(Image),
  'phone' : IDL.Text,
});
export const EducationPost = IDL.Record({
  'id' : IDL.Nat,
  'postType' : IDL.Variant({
    'video' : IDL.Null,
    'text' : IDL.Null,
    'photo' : IDL.Null,
  }),
  'contentAr' : IDL.Text,
  'contentEn' : IDL.Text,
  'isPublished' : IDL.Bool,
  'authorName' : IDL.Text,
  'publishedAt' : IDL.Int,
  'mediaUrls' : IDL.Vec(IDL.Text),
  'image' : IDL.Opt(Image),
  'titleAr' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'calendarLink' : IDL.Opt(IDL.Text),
  'descriptionAr' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
  'imageUrl' : IDL.Opt(IDL.Text),
  'locationAr' : IDL.Text,
  'locationEn' : IDL.Text,
  'image' : IDL.Opt(Image),
  'dateTime' : IDL.Int,
  'titleAr' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const TeamsCategory = IDL.Variant({
  'ministry' : IDL.Null,
  'volunteers' : IDL.Null,
  'choir' : IDL.Null,
  'kids' : IDL.Null,
  'youth' : IDL.Null,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'nameAr' : IDL.Text,
  'nameEn' : IDL.Text,
  'descriptionAr' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'order' : IDL.Nat,
  'category' : TeamsCategory,
  'mediaUrls' : IDL.Vec(IDL.Text),
});
export const VisionContents = IDL.Record({
  'order' : IDL.Nat,
  'bodyAr' : IDL.Text,
  'bodyEn' : IDL.Text,
  'sectionKey' : IDL.Text,
  'titleAr' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChurch' : IDL.Func([Church], [IDL.Nat], []),
  'addEducationPost' : IDL.Func([EducationPost], [IDL.Nat], []),
  'addEvent' : IDL.Func([Event], [IDL.Nat], []),
  'addTeam' : IDL.Func([Team], [IDL.Nat], []),
  'addVisionContent' : IDL.Func([VisionContents], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChurch' : IDL.Func([IDL.Nat], [], []),
  'deleteEducationPost' : IDL.Func([IDL.Nat], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteTeam' : IDL.Func([IDL.Nat], [], []),
  'deleteVisionContent' : IDL.Func([IDL.Text], [], []),
  'getAllChurches' : IDL.Func([], [IDL.Vec(Church)], ['query']),
  'getAllEducationPosts' : IDL.Func([], [IDL.Vec(EducationPost)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getAllVisionContent' : IDL.Func([], [IDL.Vec(VisionContents)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChurchById' : IDL.Func([IDL.Nat], [Church], ['query']),
  'getEducationPostById' : IDL.Func([IDL.Nat], [EducationPost], ['query']),
  'getEducationPostsByLanguage' : IDL.Func(
      [IDL.Bool],
      [
        IDL.Vec(
          IDL.Tuple(IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Text)), IDL.Text)
        ),
      ],
      ['query'],
    ),
  'getEventById' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getTeamById' : IDL.Func([IDL.Nat], [Team], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisionContentBySectionKey' : IDL.Func(
      [IDL.Text],
      [VisionContents],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChurch' : IDL.Func([Church], [], []),
  'updateEducationPost' : IDL.Func([EducationPost], [], []),
  'updateEvent' : IDL.Func([Event], [], []),
  'updateTeam' : IDL.Func([Team], [], []),
  'updateVisionContent' : IDL.Func([VisionContents], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Image = IDL.Vec(IDL.Nat8);
  const Church = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'nameAr' : IDL.Text,
    'nameEn' : IDL.Text,
    'descriptionAr' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'addressAr' : IDL.Text,
    'addressEn' : IDL.Text,
    'longitude' : IDL.Float64,
    'image' : IDL.Opt(Image),
    'phone' : IDL.Text,
  });
  const EducationPost = IDL.Record({
    'id' : IDL.Nat,
    'postType' : IDL.Variant({
      'video' : IDL.Null,
      'text' : IDL.Null,
      'photo' : IDL.Null,
    }),
    'contentAr' : IDL.Text,
    'contentEn' : IDL.Text,
    'isPublished' : IDL.Bool,
    'authorName' : IDL.Text,
    'publishedAt' : IDL.Int,
    'mediaUrls' : IDL.Vec(IDL.Text),
    'image' : IDL.Opt(Image),
    'titleAr' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'calendarLink' : IDL.Opt(IDL.Text),
    'descriptionAr' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
    'imageUrl' : IDL.Opt(IDL.Text),
    'locationAr' : IDL.Text,
    'locationEn' : IDL.Text,
    'image' : IDL.Opt(Image),
    'dateTime' : IDL.Int,
    'titleAr' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const TeamsCategory = IDL.Variant({
    'ministry' : IDL.Null,
    'volunteers' : IDL.Null,
    'choir' : IDL.Null,
    'kids' : IDL.Null,
    'youth' : IDL.Null,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'nameAr' : IDL.Text,
    'nameEn' : IDL.Text,
    'descriptionAr' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'order' : IDL.Nat,
    'category' : TeamsCategory,
    'mediaUrls' : IDL.Vec(IDL.Text),
  });
  const VisionContents = IDL.Record({
    'order' : IDL.Nat,
    'bodyAr' : IDL.Text,
    'bodyEn' : IDL.Text,
    'sectionKey' : IDL.Text,
    'titleAr' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChurch' : IDL.Func([Church], [IDL.Nat], []),
    'addEducationPost' : IDL.Func([EducationPost], [IDL.Nat], []),
    'addEvent' : IDL.Func([Event], [IDL.Nat], []),
    'addTeam' : IDL.Func([Team], [IDL.Nat], []),
    'addVisionContent' : IDL.Func([VisionContents], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChurch' : IDL.Func([IDL.Nat], [], []),
    'deleteEducationPost' : IDL.Func([IDL.Nat], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteTeam' : IDL.Func([IDL.Nat], [], []),
    'deleteVisionContent' : IDL.Func([IDL.Text], [], []),
    'getAllChurches' : IDL.Func([], [IDL.Vec(Church)], ['query']),
    'getAllEducationPosts' : IDL.Func([], [IDL.Vec(EducationPost)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getAllVisionContent' : IDL.Func([], [IDL.Vec(VisionContents)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChurchById' : IDL.Func([IDL.Nat], [Church], ['query']),
    'getEducationPostById' : IDL.Func([IDL.Nat], [EducationPost], ['query']),
    'getEducationPostsByLanguage' : IDL.Func(
        [IDL.Bool],
        [
          IDL.Vec(
            IDL.Tuple(IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Text)), IDL.Text)
          ),
        ],
        ['query'],
      ),
    'getEventById' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getTeamById' : IDL.Func([IDL.Nat], [Team], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisionContentBySectionKey' : IDL.Func(
        [IDL.Text],
        [VisionContents],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChurch' : IDL.Func([Church], [], []),
    'updateEducationPost' : IDL.Func([EducationPost], [], []),
    'updateEvent' : IDL.Func([Event], [], []),
    'updateTeam' : IDL.Func([Team], [], []),
    'updateVisionContent' : IDL.Func([VisionContents], [], []),
  });
};

export const init = ({ IDL }) => { return []; };