/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Church {
  'id' : bigint,
  'latitude' : number,
  'nameAr' : string,
  'nameEn' : string,
  'descriptionAr' : string,
  'descriptionEn' : string,
  'imageUrl' : [] | [string],
  'addressAr' : string,
  'addressEn' : string,
  'longitude' : number,
  'image' : [] | [Image],
  'phone' : string,
}
export interface EducationPost {
  'id' : bigint,
  'postType' : { 'video' : null } |
    { 'text' : null } |
    { 'photo' : null },
  'contentAr' : string,
  'contentEn' : string,
  'isPublished' : boolean,
  'authorName' : string,
  'publishedAt' : bigint,
  'mediaUrls' : Array<string>,
  'image' : [] | [Image],
  'titleAr' : string,
  'titleEn' : string,
}
export interface Event {
  'id' : bigint,
  'calendarLink' : [] | [string],
  'descriptionAr' : string,
  'descriptionEn' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
  'imageUrl' : [] | [string],
  'locationAr' : string,
  'locationEn' : string,
  'image' : [] | [Image],
  'dateTime' : bigint,
  'titleAr' : string,
  'titleEn' : string,
}
export type Image = Uint8Array;
export interface Team {
  'id' : bigint,
  'nameAr' : string,
  'nameEn' : string,
  'descriptionAr' : string,
  'descriptionEn' : string,
  'order' : bigint,
  'category' : TeamsCategory,
  'mediaUrls' : Array<string>,
}
export type TeamsCategory = { 'ministry' : null } |
  { 'volunteers' : null } |
  { 'choir' : null } |
  { 'kids' : null } |
  { 'youth' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisionContents {
  'order' : bigint,
  'bodyAr' : string,
  'bodyEn' : string,
  'sectionKey' : string,
  'titleAr' : string,
  'titleEn' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChurch' : ActorMethod<[Church], bigint>,
  'addEducationPost' : ActorMethod<[EducationPost], bigint>,
  'addEvent' : ActorMethod<[Event], bigint>,
  'addTeam' : ActorMethod<[Team], bigint>,
  'addVisionContent' : ActorMethod<[VisionContents], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChurch' : ActorMethod<[bigint], undefined>,
  'deleteEducationPost' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteTeam' : ActorMethod<[bigint], undefined>,
  'deleteVisionContent' : ActorMethod<[string], undefined>,
  'getAllChurches' : ActorMethod<[], Array<Church>>,
  'getAllEducationPosts' : ActorMethod<[], Array<EducationPost>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllTeams' : ActorMethod<[], Array<Team>>,
  'getAllVisionContent' : ActorMethod<[], Array<VisionContents>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChurchById' : ActorMethod<[bigint], Church>,
  'getEducationPostById' : ActorMethod<[bigint], EducationPost>,
  'getEducationPostsByLanguage' : ActorMethod<
    [boolean],
    Array<[string, string, [] | [Array<string>], string]>
  >,
  'getEventById' : ActorMethod<[bigint], Event>,
  'getTeamById' : ActorMethod<[bigint], Team>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisionContentBySectionKey' : ActorMethod<[string], VisionContents>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChurch' : ActorMethod<[Church], undefined>,
  'updateEducationPost' : ActorMethod<[EducationPost], undefined>,
  'updateEvent' : ActorMethod<[Event], undefined>,
  'updateTeam' : ActorMethod<[Team], undefined>,
  'updateVisionContent' : ActorMethod<[VisionContents], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];