/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Team {
    id: bigint;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    order: bigint;
    category: TeamsCategory;
    mediaUrls: Array<string>;
}
export interface Church {
    id: bigint;
    latitude: number;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    imageUrl?: string;
    addressAr: string;
    addressEn: string;
    longitude: number;
    image?: Image;
    phone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Image = Uint8Array;
export interface Event {
    id: bigint;
    calendarLink?: string;
    descriptionAr: string;
    descriptionEn: string;
    isPublished: boolean;
    createdAt: bigint;
    imageUrl?: string;
    locationAr: string;
    locationEn: string;
    image?: Image;
    dateTime: bigint;
    titleAr: string;
    titleEn: string;
}
export interface EducationPost {
    id: bigint;
    postType: Variant_video_text_photo;
    contentAr: string;
    contentEn: string;
    isPublished: boolean;
    authorName: string;
    publishedAt: bigint;
    mediaUrls: Array<string>;
    image?: Image;
    titleAr: string;
    titleEn: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VisionContents {
    order: bigint;
    bodyAr: string;
    bodyEn: string;
    sectionKey: string;
    titleAr: string;
    titleEn: string;
}
export interface UserProfile {
    name: string;
}
export enum TeamsCategory {
    ministry = "ministry",
    volunteers = "volunteers",
    choir = "choir",
    kids = "kids",
    youth = "youth"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_video_text_photo {
    video = "video",
    text = "text",
    photo = "photo"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChurch(church: Church): Promise<bigint>;
    addEducationPost(post: EducationPost): Promise<bigint>;
    addEvent(event: Event): Promise<bigint>;
    addTeam(team: Team): Promise<bigint>;
    addVisionContent(content: VisionContents): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteChurch(id: bigint): Promise<void>;
    deleteEducationPost(id: bigint): Promise<void>;
    deleteEvent(id: bigint): Promise<void>;
    deleteTeam(id: bigint): Promise<void>;
    deleteVisionContent(sectionKey: string): Promise<void>;
    getAllChurches(): Promise<Array<Church>>;
    getAllEducationPosts(): Promise<Array<EducationPost>>;
    getAllEvents(): Promise<Array<Event>>;
    getAllTeams(): Promise<Array<Team>>;
    getAllVisionContent(): Promise<Array<VisionContents>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChurchById(id: bigint): Promise<Church>;
    getEducationPostById(id: bigint): Promise<EducationPost>;
    getEducationPostsByLanguage(isArabic: boolean): Promise<Array<[string, string, Array<string> | null, string]>>;
    getEventById(id: bigint): Promise<Event>;
    getTeamById(id: bigint): Promise<Team>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisionContentBySectionKey(sectionKey: string): Promise<VisionContents>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateChurch(church: Church): Promise<void>;
    updateEducationPost(post: EducationPost): Promise<void>;
    updateEvent(event: Event): Promise<void>;
    updateTeam(team: Team): Promise<void>;
    updateVisionContent(content: VisionContents): Promise<void>;
}
import type { Church as _Church, EducationPost as _EducationPost, Event as _Event, Image as _Image, Team as _Team, TeamsCategory as _TeamsCategory, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChurch(arg0: Church): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChurch(to_candid_Church_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChurch(to_candid_Church_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEducationPost(arg0: EducationPost): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEducationPost(to_candid_EducationPost_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEducationPost(to_candid_EducationPost_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEvent(arg0: Event): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(to_candid_Event_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(to_candid_Event_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTeam(arg0: Team): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeam(to_candid_Team_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeam(to_candid_Team_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addVisionContent(arg0: VisionContents): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVisionContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVisionContent(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteChurch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChurch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChurch(arg0);
            return result;
        }
    }
    async deleteEducationPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEducationPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEducationPost(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteTeam(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeam(arg0);
            return result;
        }
    }
    async deleteVisionContent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVisionContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVisionContent(arg0);
            return result;
        }
    }
    async getAllChurches(): Promise<Array<Church>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChurches();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChurches();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEducationPosts(): Promise<Array<EducationPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEducationPosts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEducationPosts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeams();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeams();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVisionContent(): Promise<Array<VisionContents>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVisionContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVisionContent();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChurchById(arg0: bigint): Promise<Church> {
        if (this.processError) {
            try {
                const result = await this.actor.getChurchById(arg0);
                return from_candid_Church_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChurchById(arg0);
            return from_candid_Church_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEducationPostById(arg0: bigint): Promise<EducationPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getEducationPostById(arg0);
                return from_candid_EducationPost_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEducationPostById(arg0);
            return from_candid_EducationPost_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEducationPostsByLanguage(arg0: boolean): Promise<Array<[string, string, Array<string> | null, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEducationPostsByLanguage(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEducationPostsByLanguage(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventById(arg0: bigint): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventById(arg0);
                return from_candid_Event_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventById(arg0);
            return from_candid_Event_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamById(arg0: bigint): Promise<Team> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamById(arg0);
                return from_candid_Team_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamById(arg0);
            return from_candid_Team_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisionContentBySectionKey(arg0: string): Promise<VisionContents> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisionContentBySectionKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisionContentBySectionKey(arg0);
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateChurch(arg0: Church): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChurch(to_candid_Church_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChurch(to_candid_Church_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEducationPost(arg0: EducationPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEducationPost(to_candid_EducationPost_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEducationPost(to_candid_EducationPost_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(to_candid_Event_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(to_candid_Event_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTeam(arg0: Team): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeam(to_candid_Team_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeam(to_candid_Team_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateVisionContent(arg0: VisionContents): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisionContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisionContent(arg0);
            return result;
        }
    }
}
function from_candid_Church_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Church): Church {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_EducationPost_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationPost): EducationPost {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_TeamsCategory_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamsCategory): TeamsCategory {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Image]): Image | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    latitude: number;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    imageUrl: [] | [string];
    addressAr: string;
    addressEn: string;
    longitude: number;
    image: [] | [_Image];
    phone: string;
}): {
    id: bigint;
    latitude: number;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    imageUrl?: string;
    addressAr: string;
    addressEn: string;
    longitude: number;
    image?: Image;
    phone: string;
} {
    return {
        id: value.id,
        latitude: value.latitude,
        nameAr: value.nameAr,
        nameEn: value.nameEn,
        descriptionAr: value.descriptionAr,
        descriptionEn: value.descriptionEn,
        imageUrl: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.imageUrl)),
        addressAr: value.addressAr,
        addressEn: value.addressEn,
        longitude: value.longitude,
        image: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.image)),
        phone: value.phone
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    postType: {
        video: null;
    } | {
        text: null;
    } | {
        photo: null;
    };
    contentAr: string;
    contentEn: string;
    isPublished: boolean;
    authorName: string;
    publishedAt: bigint;
    mediaUrls: Array<string>;
    image: [] | [_Image];
    titleAr: string;
    titleEn: string;
}): {
    id: bigint;
    postType: Variant_video_text_photo;
    contentAr: string;
    contentEn: string;
    isPublished: boolean;
    authorName: string;
    publishedAt: bigint;
    mediaUrls: Array<string>;
    image?: Image;
    titleAr: string;
    titleEn: string;
} {
    return {
        id: value.id,
        postType: from_candid_variant_n29(_uploadFile, _downloadFile, value.postType),
        contentAr: value.contentAr,
        contentEn: value.contentEn,
        isPublished: value.isPublished,
        authorName: value.authorName,
        publishedAt: value.publishedAt,
        mediaUrls: value.mediaUrls,
        image: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.image)),
        titleAr: value.titleAr,
        titleEn: value.titleEn
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    calendarLink: [] | [string];
    descriptionAr: string;
    descriptionEn: string;
    isPublished: boolean;
    createdAt: bigint;
    imageUrl: [] | [string];
    locationAr: string;
    locationEn: string;
    image: [] | [_Image];
    dateTime: bigint;
    titleAr: string;
    titleEn: string;
}): {
    id: bigint;
    calendarLink?: string;
    descriptionAr: string;
    descriptionEn: string;
    isPublished: boolean;
    createdAt: bigint;
    imageUrl?: string;
    locationAr: string;
    locationEn: string;
    image?: Image;
    dateTime: bigint;
    titleAr: string;
    titleEn: string;
} {
    return {
        id: value.id,
        calendarLink: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.calendarLink)),
        descriptionAr: value.descriptionAr,
        descriptionEn: value.descriptionEn,
        isPublished: value.isPublished,
        createdAt: value.createdAt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.imageUrl)),
        locationAr: value.locationAr,
        locationEn: value.locationEn,
        image: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.image)),
        dateTime: value.dateTime,
        titleAr: value.titleAr,
        titleEn: value.titleEn
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    order: bigint;
    category: _TeamsCategory;
    mediaUrls: Array<string>;
}): {
    id: bigint;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    order: bigint;
    category: TeamsCategory;
    mediaUrls: Array<string>;
} {
    return {
        id: value.id,
        nameAr: value.nameAr,
        nameEn: value.nameEn,
        descriptionAr: value.descriptionAr,
        descriptionEn: value.descriptionEn,
        order: value.order,
        category: from_candid_TeamsCategory_n36(_uploadFile, _downloadFile, value.category),
        mediaUrls: value.mediaUrls
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, string, [] | [Array<string>], string]): [string, string, Array<string> | null, string] {
    return [
        value[0],
        value[1],
        from_candid_opt_n43(_uploadFile, _downloadFile, value[2]),
        value[3]
    ];
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    text: null;
} | {
    photo: null;
}): Variant_video_text_photo {
    return "video" in value ? Variant_video_text_photo.video : "text" in value ? Variant_video_text_photo.text : "photo" in value ? Variant_video_text_photo.photo : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ministry: null;
} | {
    volunteers: null;
} | {
    choir: null;
} | {
    kids: null;
} | {
    youth: null;
}): TeamsCategory {
    return "ministry" in value ? TeamsCategory.ministry : "volunteers" in value ? TeamsCategory.volunteers : "choir" in value ? TeamsCategory.choir : "kids" in value ? TeamsCategory.kids : "youth" in value ? TeamsCategory.youth : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Church>): Array<Church> {
    return value.map((x)=>from_candid_Church_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EducationPost>): Array<EducationPost> {
    return value.map((x)=>from_candid_EducationPost_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, string, [] | [Array<string>], string]>): Array<[string, string, Array<string> | null, string]> {
    return value.map((x)=>from_candid_tuple_n42(_uploadFile, _downloadFile, x));
}
function to_candid_Church_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Church): _Church {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_EducationPost_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationPost): _EducationPost {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Event_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): _Event {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Team_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Team): _Team {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_TeamsCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamsCategory): _TeamsCategory {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    postType: Variant_video_text_photo;
    contentAr: string;
    contentEn: string;
    isPublished: boolean;
    authorName: string;
    publishedAt: bigint;
    mediaUrls: Array<string>;
    image?: Image;
    titleAr: string;
    titleEn: string;
}): {
    id: bigint;
    postType: {
        video: null;
    } | {
        text: null;
    } | {
        photo: null;
    };
    contentAr: string;
    contentEn: string;
    isPublished: boolean;
    authorName: string;
    publishedAt: bigint;
    mediaUrls: Array<string>;
    image: [] | [_Image];
    titleAr: string;
    titleEn: string;
} {
    return {
        id: value.id,
        postType: to_candid_variant_n12(_uploadFile, _downloadFile, value.postType),
        contentAr: value.contentAr,
        contentEn: value.contentEn,
        isPublished: value.isPublished,
        authorName: value.authorName,
        publishedAt: value.publishedAt,
        mediaUrls: value.mediaUrls,
        image: value.image ? candid_some(value.image) : candid_none(),
        titleAr: value.titleAr,
        titleEn: value.titleEn
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    calendarLink?: string;
    descriptionAr: string;
    descriptionEn: string;
    isPublished: boolean;
    createdAt: bigint;
    imageUrl?: string;
    locationAr: string;
    locationEn: string;
    image?: Image;
    dateTime: bigint;
    titleAr: string;
    titleEn: string;
}): {
    id: bigint;
    calendarLink: [] | [string];
    descriptionAr: string;
    descriptionEn: string;
    isPublished: boolean;
    createdAt: bigint;
    imageUrl: [] | [string];
    locationAr: string;
    locationEn: string;
    image: [] | [_Image];
    dateTime: bigint;
    titleAr: string;
    titleEn: string;
} {
    return {
        id: value.id,
        calendarLink: value.calendarLink ? candid_some(value.calendarLink) : candid_none(),
        descriptionAr: value.descriptionAr,
        descriptionEn: value.descriptionEn,
        isPublished: value.isPublished,
        createdAt: value.createdAt,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        locationAr: value.locationAr,
        locationEn: value.locationEn,
        image: value.image ? candid_some(value.image) : candid_none(),
        dateTime: value.dateTime,
        titleAr: value.titleAr,
        titleEn: value.titleEn
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    order: bigint;
    category: TeamsCategory;
    mediaUrls: Array<string>;
}): {
    id: bigint;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    order: bigint;
    category: _TeamsCategory;
    mediaUrls: Array<string>;
} {
    return {
        id: value.id,
        nameAr: value.nameAr,
        nameEn: value.nameEn,
        descriptionAr: value.descriptionAr,
        descriptionEn: value.descriptionEn,
        order: value.order,
        category: to_candid_TeamsCategory_n17(_uploadFile, _downloadFile, value.category),
        mediaUrls: value.mediaUrls
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    latitude: number;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    imageUrl?: string;
    addressAr: string;
    addressEn: string;
    longitude: number;
    image?: Image;
    phone: string;
}): {
    id: bigint;
    latitude: number;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    descriptionEn: string;
    imageUrl: [] | [string];
    addressAr: string;
    addressEn: string;
    longitude: number;
    image: [] | [_Image];
    phone: string;
} {
    return {
        id: value.id,
        latitude: value.latitude,
        nameAr: value.nameAr,
        nameEn: value.nameEn,
        descriptionAr: value.descriptionAr,
        descriptionEn: value.descriptionEn,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        addressAr: value.addressAr,
        addressEn: value.addressEn,
        longitude: value.longitude,
        image: value.image ? candid_some(value.image) : candid_none(),
        phone: value.phone
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_video_text_photo): {
    video: null;
} | {
    text: null;
} | {
    photo: null;
} {
    return value == Variant_video_text_photo.video ? {
        video: null
    } : value == Variant_video_text_photo.text ? {
        text: null
    } : value == Variant_video_text_photo.photo ? {
        photo: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamsCategory): {
    ministry: null;
} | {
    volunteers: null;
} | {
    choir: null;
} | {
    kids: null;
} | {
    youth: null;
} {
    return value == TeamsCategory.ministry ? {
        ministry: null
    } : value == TeamsCategory.volunteers ? {
        volunteers: null
    } : value == TeamsCategory.choir ? {
        choir: null
    } : value == TeamsCategory.kids ? {
        kids: null
    } : value == TeamsCategory.youth ? {
        youth: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
